apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp
spec:
  selector:
    matchLabels:
      app: yourapp
  replicas: 2
  template:
    metadata:
      labels:
        app: yourapp
    spec:
      containers:
      - name: yourapp
        image: simpleimage/argocd-app:1.1
        ports:
        - containerPort: 8080

